server:
  port: 9010

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379

---
# 테스트일 때는 포트번호 63790을 사용하겠다.
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: 127.0.0.1
      port: 63790
